// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1bpFBZr5bDNNbIrPKRBi4BumqKBgQDeo',
    appId: '1:69778231001:web:6d43096e3cd96b4cf038c8',
    messagingSenderId: '69778231001',
    projectId: 'ecollege-8156b',
    authDomain: 'ecollege-8156b.firebaseapp.com',
    storageBucket: 'ecollege-8156b.firebasestorage.app',
    measurementId: 'G-35JQ80SRHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcxy1begazN7YIFgfsqTfeOx6Lpec9UBQ',
    appId: '1:69778231001:android:3077f3977beffad5f038c8',
    messagingSenderId: '69778231001',
    projectId: 'ecollege-8156b',
    storageBucket: 'ecollege-8156b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcV3dQ3bqoRTw9Y08LqjGj0Jutw8r41hs',
    appId: '1:69778231001:ios:3d39027fc1798447f038c8',
    messagingSenderId: '69778231001',
    projectId: 'ecollege-8156b',
    storageBucket: 'ecollege-8156b.firebasestorage.app',
    iosBundleId: 'com.example.ecollege',
  );
}
